### ISSUE TITLE
os package manager should be generic

### ISSUE THREAD

**Issue by shinsekai** [Wefactorit/ans_puib#6]
Currently, **_ans_puib_** module is working fine on CentOS and Debian OS distribution thanks to code below:

**_roles/image_builder/templates/template.json.j2_**

```  
{% if 'centos' in mytemplate -%}
     {% for item in command_rehl %}
         {{ item }}
     {% endfor %}
{% elif 'ubuntu'in mytemplate %}
     {% for item in command_debian%}
         {{ item }}
    {% endfor %}
{% endif %} 
```

**_roles/packer/tasks/main.yml_**

```
#UBUNTU
- name: install git/gitflow/wget/unzip/vim
  apt:
   name: "{{ item }}"
  with_items:
   - git
   - vim
   - wget
   - unzip
  when: ansible_distribution == "Ubuntu"

#CENTOS
- name: install  git/gitflow/wget/unzip/vim
  yum:
   name: "{{ item }}"
  with_items:
   - git
   - vim
   - wget
   - unzip
  when: ansible_distribution == "CentOS"
```

Nevertheless, it could be more generic, if we could use [Ansible Package Module](https://docs.ansible.com/ansible/latest/modules/package_module.html) instead of having specific code for each OS we have and their related package managers such as yum and apt in this case.
